import {
  pdf1,
  home5,
  chair1,
  chair2,
  chair3,
  chair4,
  chair10,
  chair6,
  chair7,
  chair8,
  chair9,
  chair11,
  shofa1,
  shofa2,
  shofa3,
  sofa4,
  chair5,
  set1,
  set2,
  set3,
  set4,
  sofa5,
  sofa12,
  sofa10,
  bed2,
  bed1,
  bed3,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: chair1,
    productName: "imprimante",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "202",
    img:chair2,
    productName: "imprimante",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "203",
    img: chair3,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "204",
    img: chair4,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "205",
    img: chair5,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "206",
    img: chair6,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "207",
    img: chair7,
    productName: "imprimante",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "208",
    img: chair8,
    productName: "imprimante",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "imprimante",
  },
  {
    _id: "209",
    img: chair9,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "210",
    img: chair10,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "211",
    img: chair11,
    productName: "encre",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "212",
    img: shofa1,
    productName: "encre",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "ancre",
  },
  {
    _id: "213",
    img: shofa2,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "214",
    img: shofa3,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "215",
    img: sofa4,
    productName: "Ruban",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "216",
    img: home5,
    productName: "Ruban",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Ruban",
  },
  {
    _id: "217",
    img: home5,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "219",
    img: home5,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "220",
    img: home5,
    productName: "Bac de dechet",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
  {
    _id: "221",
    img: home5,
    productName: "Bac de dechet",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = 
  
  [
    {
      _id: "203",
      img: set2,
      productName: "Elegant Prints Collection",
      price: "450",
      color: "Blanc",
      badge: true,
      brand: "Furnitech",
      des: "Discover the epitome of luxury with our Elegant Prints Collection. Featuring timeless designs and impeccable craftsmanship, this collection is a statement of sophistication for your home or office space.",
      cat: "Imprimante",
      pdf: pdf1,
    },
    {
      _id: "2005",
      img: chair2,
      productName: "Regal Chairs",
      price: "450",
      color: "Blanc",
      badge: true,
      brand: "Furnitech",
      des: "Indulge in comfort and style with our Regal Chairs. Designed for both aesthetics and comfort, these chairs are the perfect addition to elevate any room’s ambiance.",
      cat: "Imprimante",
      pdf: pdf1,
    },
    {
      _id: "20005",
      img: bed3,
      productName: "Serenity Dream Bed",
      price: "450",
      color: "Blanc",
      badge: false,
      brand: "Furnitech",
      des: "Create your dream space with the Serenity Dream Bed. Crafted with utmost care and attention to detail, this bed promises serene nights and beautiful mornings.",
      cat: "Imprimante",
      pdf: pdf1,
    },
    {
      _id: "206",
      img: shofa2,
      productName: "Luxe Sanctuary Shofa Set",
      price: "450",
      color: "Blanc",
      badge: true,
      brand: "Furnitech",
      des: "Transform your living space with the Luxe Sanctuary Shofa Set. Immerse yourself in luxurious comfort and timeless elegance with this impeccably crafted centerpiece.",
      pdf: pdf1,
    },
    {
      _id: "207",
      img: chair3,
      productName: "Regal Throne Chair",
      price: "450",
      color: "Blanc",
      badge: true,
      brand: "Furnitech",
      des: "Experience the ultimate in regal comfort with our Regal Throne Chair. Designed for royalty, this chair blends opulence with practicality for a truly majestic seating experience.",
      pdf: pdf1,
    },
    {
      _id: "208",
      img: set3,
      productName: "Luxe Elegance Set",
      price: "450",
      color: "Blanc",
      badge: false,
      brand: "Furnitech",
      des: "Embrace elegance with our Luxe Elegance Set. Crafted with premium materials and exquisite detailing, this set elevates your living space to new heights of sophistication.",
      pdf: pdf1,
    },
    {
      _id: "233",
      img: shofa3,
      productName: "Premium Sofa",
      price: "450",
      color: "Blanc",
      badge: true,
      brand: "Furnitech",
      des: "Discover unparalleled comfort and style with our Premium Sofa. Designed to enhance any interior, this sofa combines luxurious upholstery with superior craftsmanship.",
      pdf: pdf1,
      ficheTech: [],
    },
    {
      _id: "220",
      img: chair4,
      productName: "Blacky Chairs",
      price: "25.00",
      color: "Mixed",
      badge: false,
      des: "Upgrade your seating with Blacky Chairs. Combining modern aesthetics with ergonomic design, these chairs offer both comfort and style for any setting.",
      cat: "Bac",
    },
    {
      _id: "221",
      img: set4,
      productName: "Imperial Majesty Collection",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Step into luxury with the Imperial Majesty Collection. Crafted with attention to detail and elegance, this collection adds a touch of grandeur to your living space.",
      cat: "Bac",
    },
    {
      _id: "215",
      img: sofa5,
      productName: "Premium Sofa",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Experience comfort and style with our Premium Sofa. Designed to enhance relaxation and elevate your decor, it's a perfect addition to any modern living space.",
      cat: "Ruban",
    },
    {
      _id: "216",
      img: chair6,
      productName: "Premium Chairs",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Upgrade your seating with Premium Chairs. With sleek design and premium materials, these chairs offer exceptional comfort and style for your home or office.",
      cat: "Ruban",
    },
    {
      _id: "209",
      img: set4,
      productName: "Premium Collection",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Enhance your decor with our Premium Collection. Featuring modern design and quality craftsmanship, this collection brings sophistication to any room.",
      cat: "Encre",
    },
    {
      _id: "210",
      img: chair11,
      productName: "Royal Chairs",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Feel like royalty with our Royal Chairs. Designed for comfort and elegance, these chairs add a touch of luxury to your living or workspace.",
      cat: "Encre",
    },
    {
      _id: "211",
      img: sofa12,
      productName: "Luxury Sofa",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Indulge in luxury with our Luxury Sofa. Crafted with plush upholstery and modern design, it's perfect for creating a cozy yet stylish ambiance.",
      cat: "Encre",
    },
    {
      _id: "212",
      img: bed1,
      productName: "Dreamscape Bed",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Sleep in style with our Dreamscape Bed. Designed for comfort and elegance, this bed transforms your bedroom into a serene sanctuary.",
      cat: "Encre",
    },
    {
      _id: "213",
      img: sofa10,
      productName: "Premium Sofa",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Upgrade your seating with our Premium Sofa. With contemporary design and plush comfort, it's an essential piece for modern living.",
      cat: "Ruban",
    },
    {
      _id: "214",
      img: chair10,
      productName: "Regal Chairs",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Experience regal comfort with our Regal Chairs. Combining luxury and functionality, these chairs enhance any space with their sophisticated design.",
      cat: "Ruban",
    },
    {
      _id: "217",
      img: bed2,
      productName: "Serenity Dream Bed",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Transform your bedroom into a serene retreat with our Serenity Dream Bed. Crafted for comfort and style, it ensures restful nights and peaceful mornings.",
      cat: "Bac",
    },
    {
      _id: "219",
      img: chair4,
      productName: "Elegant Chairs",
      price: "220.00",
      color: "Black",
      badge: false,
      des: "Add elegance to your space with our Elegant Chairs. Designed for comfort and style, they elevate any room with their refined craftsmanship.",
      cat: "Bac",
    },
  ]
  
  
  // =================== imprimante hp =================

//   {
//     _id: "hp1",
//     img: hp1,
//     productName:
//       "IMPRIMANTE HP JET D'ENCRE HP SMART TANK 516 COULEUR MFP 3EN1 A4 WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Desc : Imprimante Jet D'encre HP SMART TANK 516 3en1 Couleur 3YW70A - Fonction: Impression, Copie, Numérisation - Technologie d'impression: jet d'encre - Vitesse d'impression Noir : Jusqu'à 22 ppm - Vitesse d’impression Couleur : Jusqu'à 16 ppm - Résolution d'impression Couleur : 1200x1200dpi - Format Papier : A4 - Capacité Papier : 100 feuilles -  Cycle d'utilisation (mensuel, A4) : Jusqu'à 1000pages - Connectivité: USB 2.0 haute vitesse, Wi-Fi, Bluetooth LE -  Dimensions: 447 x 373 x 158 mm - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "3YW70A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Ecran", value: "LCD" },
//       {
//         label: "Taille de L écran cm",
//         value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Technologie d impression", value: "Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Impression", value: "Couleur" },
//       { label: "formats", value: "A4" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
//       { label: "FAX", value: "Non" },
//       { label: "Mémoire", value: "256 Mo" },
//       {
//         label: "Qualité d impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 ppp",
//       },
//       {
//         label: "Qualité d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 ppp",
//       },
//       { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Connectivite", value: "USB 2.0, WiFi" },
//       { label: "Capacité papier", value: "100 feuilles" },
//       { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
//       {
//         label: "Consommation électrique",
//         value:
//           "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
//       },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
//       },
//       { label: "Poids", value: "5,14 kg" },
//       { label: "Dimensions", value: "447 x 373 x 158 mm" },
//       { label: "Couleur", value: "Noir et Bleu" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "hp2",
//     img: hp2,
//     productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Desc : Imprimante Multifonction Jet d'encre 3 en 1 à réservoir intégré - Impression, numérisation, copie, sans fil - Résolution d'impression: Jusqu'à 4800 x 1200 dpi - Vitesse d'impression Couleur Jusqu'à 15 ppm -Vitesse d'impression N et B Jusqu'à 18 ppm - Résolution du scanner: 1200 x 1200 dpi - Format A4 - Interface USB - Bac d'alimentation de 60 feuilles - Dimensions: 525 x 310 x 158 mm - Garantie 1 an (+ Extension de Garantie 2 Ans ) + 5 Bouteilles",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [],
//   },

//   {
//     _id: "hp3",
//     img: hp3,
//     productName: "IMPRIMANTE HP INK TANK WIRELESS 415 ALL-IN-ONE",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Hp",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   // =================== imprimante ricoh =================
//   {
//     _id: "ricoh1",
//     img: ricoh1,
//     productName: "IMPRIMANTE RICOH P501",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "ricoh2",
//     img: ricoh2,
//     productName: "IMPRIMANTE RICOH SP3710DN",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh3",
//     img: ricoh3,
//     productName: "IMPRIMANTE RICOH SP4520DN",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh4",
//     img: ricoh4,
//     productName: "IMPRIMANTE RICOH COULEUR LASER SPC840",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
//   {
//     _id: "ricoh5",
//     img: ricoh5,
//     productName: "IMPRIMANTE RICOH SP4510DN (407313)",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Ricoh",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   // =================== imprimante ricoh =================

//   {
//     _id: "espson1",
//     img: espson1,
//     productName: "IMPRIMANTE EPSON L3251 3EN1 A4 WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Epson",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },

//   {
//     _id: "espson2",
//     img: espson2,
//     productName: "IMPRIMANTE EPSON JET D'ENCRE L3156 COULEUR A4  WIFI",
//     price: "450",
//     color: "Blanc",
//     badge: true,
//     brand: "Epson",
//     des: "Imprimante à Réservoir intégré HP Ink Tank 315 - Fonctions: Impression, copier, Numérisation - Format Papier: A4 - Technologie d'impression: jet d'encre thermique HP - Vitesse d'impression: Jusqu'à 19 ppm (Noir), Jusqu'à 15 ppm (couleur) - Résolution d'impression: 1200 x 1200 dpi(couleur), 4800 x 1200 dpi(noir) - Vitesse de copie(A4, ISO): 6,5 cpm Noir; 2 cpm Couleur - Vitesse de numérisation A4: Jusqu'à 21 secondes - Impression recto verso Manuelle - Formats de fichiers pour la numérisation: JPEG, TIFF, PDF, BMP, PNG - Vitesse du processeur: 360 MHz - Connectivité: USB  - Dimensions: 525 x 310 x 158 mm - Poids: 4,67 kg - Garantie: 1 an",
//     cat: "Imprimante",
//     pdf: pdf1,
//     ficheTech: [
//       { label: "DISPONIBILITÉ", value: "En stock" },
//       { label: "gtin", value: "Z4B04A" },
//       { label: "Marque", value: "HP" },
//       { label: "Destockage", value: "Non" },
//       { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
//       { label: "fonctions", value: "Multifonction" },
//       { label: "Impression", value: "Couleur" },
//       { label: "Mémoire", value: "Non" },
//       { label: "FAX", value: "Non" },
//       { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
//       { label: "Chargement de Documents", value: "Oui" },
//       { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
//       { label: "Vitesse du Processeur", value: "360 MHz" },
//       {
//         label: "Impression sans bordure",
//         value: "Oui, jusqu’à 210 x 297 mm (A4)",
//       },
//       { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
//       { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
//       {
//         label: "Résolution d'impression Noir",
//         value: "Jusqu'à 1 200 x 1 200 DPI",
//       },
//       {
//         label: "Résolution d impression Couleur",
//         value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       {
//         label: "Résolution d impression",
//         value:
//           "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
//       },
//       { label: "Type de Scanner", value: "Scanner à Plat" },
//       { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
//       { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
//       {
//         label: "Résolution de numérisation optimisée",
//         value: "Jusqu’à 1200 ppp",
//       },
//       { label: "Recto/Verso", value: "Manuel" },
//       { label: "Connectivite", value: "USB" },
//       { label: "formats", value: "A4" },
//       {
//         label: "Premiére Page Imprimée",
//         value:
//           "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
//       },
//       {
//         label: "Alimentation-courant",
//         value:
//           "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
//       },
//       {
//         label: "Type de Papier pris en charge",
//         value:
//           "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
//       },
//       {
//         label: "Consommation électrique",
//         value:
//           "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
//       },
//       {
//         label: "Cycle d utilisation Mensuel",
//         value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
//       },
//       {
//         label: "Alimentation papier standard",
//         value:
//           "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
//       },
//       { label: "Ecran Tactile", value: "Non" },
//       { label: "Type ecran", value: "7 segments et icône LCD" },
//       {
//         label: "Volume de Pages Mensuel Recommandé",
//         value: "400 à 800 (Jusqu'à 1000 pages)",
//       },
//       { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
//       { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
//       { label: "Grammage", value: "75 g/m²" },
//       {
//         label: "Contenu de L'emballage",
//         value:
//           "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
//       },
//       { label: "Poids", value: "4,67 kg" },
//       { label: "Couleur", value: "Noir" },
//       { label: "Dimensions", value: "525 x 310 x 158 mm" },
//       { label: "Garantie", value: "1 an" },
//     ],
//   },
// ];
